# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package NuGet
      run: dotnet pack -c Release -o . src/fstonge.AspNetCore.Routing.Translation/fstonge.AspNetCore.Routing.Translation.csproj
    - name: Publish NuGet
      run: dotnet nuget push src/fstonge.AspNetCore.Routing.Translation/fstonge.AspNetCore.Routing.Translation.nupkg -k ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
    - name: Package NuGet
      run: dotnet pack -c Release -o . src/fstonge.AspNetCore.Session.Distributed/fstonge.AspNetCore.Session.Distributed.csproj 
    - name: Publish NuGet
      run: dotnet nuget push src/fstonge.AspNetCore.Session.Distributed/fstonge.AspNetCore.Session.Distributed.nupkg -k ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json
